# render.yaml
# Ensure this file is in the root of your Git repository.

services:
  # Backend Service
  - type: web
    name: kabyle-asr-backend
    env: python
    # CORRECTED: Since 'dir: backend' is set, the working directory
    # for this command is already 'backend/'. So, just 'requirements.txt' is needed.
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    dir: backend
    plan: free # Ensure this is 'free' if you're on the free tier

  # Frontend Service
  - type: web
    name: kabyle-asr-frontend
    env: static
    buildCommand: "npm install && npm run build"
    publishPath: frontend/build
    dir: frontend