# render.yaml
# Ensure this file is in the root of your Git repository.

services:
  # Backend Service
  - type: web
    name: kabyle-asr-backend
    env: python
    # Explicitly run the build.sh script from the backend directory
    # This is the most robust way to ensure the correct working directory for the build command.
    buildCommand: "cd backend && bash build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    # The 'dir' field is still important for the overall service context,
    # but we're being explicit in buildCommand.
    dir: backend
    plan: free # Ensure this is 'free' if you're on the free tier

  # Frontend Service
  - type: web
    name: kabyle-asr-frontend
    env: static
    buildCommand: "npm install && npm run build"
    publishPath: frontend/build
    dir: frontend