# render.yaml
# This file defines the services for Render deployment.

services:
  # Backend Service (now located in the root directory)
  - type: web
    name: kabyle-asr-backend
    env: python
    buildCommand: "pip install -r requirements.txt" # Path is now relative to the root
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    # The 'dir' property is removed for the backend as its files are in the root.
    plan: free # Using the free plan

  # Frontend Service (remains in its 'frontend' directory)
  - type: web
    name: kabyle-asr-frontend
    env: static
    buildCommand: "npm install && npm run build"
    publishPath: frontend/build
    dir: frontend # Still needed for the frontend service
