# render.yaml
# Ensure this file is in the root of your Git repository.

services:
  # Backend Service
  - type: web
    name: kabyle-asr-backend
    env: python
    # Change buildCommand to execute the new shell script
    buildCommand: "bash backend/build.sh" 
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    dir: backend
    plan: free

  # Frontend Service
  - type: web
    name: kabyle-asr-frontend
    env: static
    buildCommand: "npm install && npm run build"
    publishPath: frontend/build
    dir: frontend