services:
  # Backend Service
  - type: web
    name: kabyle-asr-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app" # Using Gunicorn for production
    dir: backend
    plan: starter # Use a paid plan for better performance and to avoid cold starts.

  # Frontend Service
  - type: web
    name: kabyle-asr-frontend
    env: static
    buildCommand: "npm install && npm run build"
    publishPath: frontend/build
    dir: frontend
